// import type { NextPage } from 'next'
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Cogs from '../src/components/cogs';
import Details from '..src/components/details';
import RearCogs from '../src/components/RearCogs';

const Home: Head = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cog Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hello</div>
      <Cogs />
      <Details />

    </div>
  )
}

export default Home
