// import type { NextPage } from 'next'
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Cogs from '../src/components/rearCogs';
import Details from '../src/components/details';
import { useCounter } from '@src/context/rearCogContext'

const Home: Head = () => {
  const { stateRear, stateFront, dispatchRear, dispatchFront } = useCounter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Cog Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hello</div>
      <Cogs handlerR={dispatchRear} handlerF={dispatchFront} {...stateRear} {...stateFront} />
      <Details {...stateRear} {...stateFront} />

    </div>
  )
}

export default Home
